# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.IntegerField(choices=[(0, 'Closed'), (1, 'Open')], default=1, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='domain',
            field=models.IntegerField(choices=[(0, 'General Acting'), (1, 'Voice Acting'), (2, 'Stage Acting'), (3, 'Special Effects'), (4, 'Stage Crew'), (5, 'Other')], verbose_name='Role'),
        ),
    ]
