# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0003_auto_20180216_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceevent',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
