# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0005_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='audition_management.Role'),
        ),
    ]
