# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0006_auto_20180321_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='auditionaccount',
            name='age',
            field=models.IntegerField(default=0, verbose_name='age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditionaccount',
            name='ethnicity',
            field=models.IntegerField(choices=[(0, 'Asian'), (1, 'Black'), (2, 'Hispanic'), (3, 'Native American'), (4, 'White')], default=4, verbose_name='ethnicity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditionaccount',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Apache Attack Helicopter')], default=1, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditionaccount',
            name='location',
            field=models.CharField(default='Narnia', max_length=512, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastwork',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastworks', to='audition_management.AuditionAccount'),
        ),
    ]
