# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0010_auto_20180327_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditionaccount',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='auditionaccount',
            name='ethnicity',
            field=models.IntegerField(blank=True, choices=[(0, 'Asian'), (1, 'Black'), (2, 'Hispanic'), (3, 'Native American'), (4, 'White')], null=True, verbose_name='ethnicity'),
        ),
        migrations.AlterField(
            model_name='auditionaccount',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male'), (2, 'Apache Attack Helicopter')], null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='auditionaccount',
            name='location',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='location'),
        ),
    ]
