# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0011_auto_20180327_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditionaccount',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True, verbose_name='gender'),
        ),
    ]
