# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0011_auto_20180327_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='studio_address',
            field=models.CharField(max_length=95, verbose_name='Studio Address'),
        ),
    ]
