# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0012_auto_20180327_1653'),
        ('audition_management', '0012_auto_20180327_2038'),
    ]

    operations = [
    ]
