# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audition_management', '0013_merge_20180329_1757'),
        ('audition_management', '0013_merge_20180329_1306'),
    ]

    operations = [
    ]
